chore: add facility details
savannahghi/mycarehub-frontend-daktari pull request #532
Opened 2022-10-03 13:24 UTC by byronkimani

- add facility details to search details view page

Signed-off-by: Byron Kimani <byronkimani@Byrons-MacBook-Pro.local>

2022-10-03 14:39 UTC, abiudrn requested changes

2022-10-03 14:39 UTC, abiudrn commented on lib/presentation/search/widgets/search_details_information_widget.dart
> +                text: userName,
A `facilityName` should be here, not the `userName`

2022-10-04 13:44 UTC, byronkimani commented on lib/presentation/search/widgets/search_details_information_widget.dart
> +                text: userName,
It was a temporary placeholder as i waited for the BE implementation. Should be changed now.

2022-10-04 14:14 UTC, abiudrn approved these changes

2022-10-04 14:16 UTC, EugeneDevv approved these changes

2022-10-04 14:17 UTC, EugeneDevv approved these changes

2022-10-04 14:17 UTC, merged