feat: link create program api
savannahghi/mycarehub-frontend-daktari pull request #623
Opened 2023-02-09 05:17 UTC by LUCYOGUTU

2023-02-09 12:46 UTC, abiudrn requested changes

2023-02-09 12:46 UTC, abiudrn commented on lib/presentation/onboarding/core/search_organization_page.dart
> +              vm.wait.isWaitingFor(fetchOrganisationsFlag)) {
Is there a reason you are checking the same condition here twice?

2023-02-09 13:04 UTC, abiudrn approved these changes

2023-02-09 13:12 UTC, byronkimani requested changes

2023-02-09 13:12 UTC, byronkimani commented on lib/application/redux/actions/program_management/create_program_action.dart
> +        Sentry.captureException(UserException(errors));
Could you use `reportErrorToSentry` It has more robust logging info

2023-02-09 13:12 UTC, byronkimani commented on lib/presentation/onboarding/core/search_organization_page.dart
> +import 'package:prohealth360_daktari/application/redux/actions/flags/app_flags.dart';
Do we need this page ?
I had previously retired this page since it was part of a retired workflow

2023-02-09 13:16 UTC, byronkimani commented on test/widget_tests/presentation/onboarding/core/search_organization_page_test.dart
> +      await tester.pump(const Duration(seconds: 2));
We could add at least one expectation here

2023-02-09 13:57 UTC, byronkimani approved these changes

2023-02-10 06:22 UTC, EugeneDevv commented on lib/presentation/router/route_generator.dart
> +          settings: const RouteSettings(name: 'Search facilities page'),
this is supposed to be ```Search Organisations Page```

2023-02-10 06:22 UTC, EugeneDevv commented on test/widget_tests/presentation/organization_management/create_program_page_test.dart
> +      expect(find.text('Field cannot be empty'), findsOneWidget);
Replace this with the ```fieldCannotBeEmptyText``` in ```app_strings.dart```. Apply this to the other expectations.

2023-02-10 12:44 UTC, EugeneDevv approved these changes

2023-02-10 12:48 UTC, byronkimani approved these changes

2023-02-10 12:49 UTC, merged