fix: facility search error message
savannahghi/mycarehub-frontend-daktari pull request #758
Opened 2023-06-27 10:05 UTC by samrasugu

![Screenshot_1687859606](https://github.com/savannahghi/mycarehub-frontend-daktari/assets/88058142/73333660-cba2-4884-a1b5-736fa4de0dbe)

2023-06-29 09:49 UTC, byronkimani requested changes

2023-06-29 09:49 UTC, byronkimani commented on lib/presentation/onboarding/core/search_facilities_page.dart
> +                              // ScaffoldMessenger.of(context)
Commented code.

2023-06-29 14:06 UTC, byronkimani approved these changes

2023-06-30 05:11 UTC, abiudrn approved these changes

2023-06-30 05:11 UTC, merged