fix: group member count
savannahghi/mycarehub-frontend-daktari pull request #765
Opened 2023-06-30 13:48 UTC by samrasugu

![Screenshot_1688132865](https://github.com/savannahghi/mycarehub-frontend-daktari/assets/88058142/b12a72d0-e402-4d29-87aa-7fdf880a1628)

2023-06-30 14:12 UTC, byronkimani approved these changes

2023-07-03 05:27 UTC, abiudrn requested changes

2023-07-03 05:27 UTC, abiudrn commented on lib/presentation/communities/pages/room_info_page.dart
> +                    ),
Extract this into a function that returns the string representation of the members. You can do the if checks in the function.

2023-07-03 08:36 UTC, EugeneDevv approved these changes

2023-07-03 08:36 UTC, abiudrn approved these changes

2023-07-03 08:36 UTC, merged