fix: assessment responses description
savannahghi/mycarehub-frontend-daktari pull request #794
Opened 2023-07-12 12:13 UTC by samrasugu

![Screenshot_1689164019](https://github.com/savannahghi/mycarehub-frontend-daktari/assets/88058142/75173158-0909-4715-8a9b-5a0df8968661)

2023-07-12 13:04 UTC, abiudrn requested changes

2023-07-13 07:38 UTC, byronkimani approved these changes

2023-07-13 07:39 UTC, byronkimani commented on lib/domain/core/value_objects/app_strings.dart
> +    "These are the clients' responses captured from the screening tool";
Resolving this since @abiudrn is away...

2023-07-13 07:41 UTC, EugeneDevv approved these changes

2023-07-13 08:04 UTC, merged