chore: list groups by recent activity
savannahghi/mycarehub-frontend-daktari pull request #816
Opened 2023-07-21 09:01 UTC by samrasugu

- Before

![Screenshot_1689924980](https://github.com/savannahghi/mycarehub-frontend-daktari/assets/88058142/b2913473-d81f-444b-be09-11ac294e7e6d)

- After

![Screenshot_1689929115](https://github.com/savannahghi/mycarehub-frontend-daktari/assets/88058142/06eca875-56fd-4d4d-836c-a8d0b67d4aee)

2023-07-21 09:08 UTC, abiudrn requested changes

2023-07-21 09:08 UTC, abiudrn commented on lib/presentation/communities/pages/room_list_page.dart
> +                          final List<Room> theRooms = sortRoomsByLastActivity(allRooms);
Rename this wariable to be `sortedRooms`

2023-07-21 09:08 UTC, abiudrn commented on lib/application/core/services/communities_helpers.dart
> +List<Room> sortRoomsByLastActivity(List<Room> rooms) {
Write tests for this function to address all the test cases specified.

Since this helper will be shared between 2 apps, move it to `sghi_core` and write tests for it

2023-07-21 09:15 UTC, abiudrn requested changes

2023-07-25 08:17 UTC, EugeneDevv approved these changes

2023-07-25 08:20 UTC, byronkimani approved these changes

2023-07-25 08:41 UTC, lucyogutu approved these changes

2023-07-26 04:22 UTC, abiudrn approved these changes

2023-07-26 07:04 UTC, merged