chore: refactor facility data class
savannahghi/mycarehub-frontend-daktari pull request #924
Opened 2023-10-02 08:29 UTC by byronkimani

- refactor facility data class

2023-10-02 09:15 UTC, abiudrn requested changes

2023-10-02 09:15 UTC, abiudrn commented on lib/domain/core/entities/facilities/coordinates.dart
> +    @JsonKey(name: 'long') String? lng,
```suggestion
    @JsonKey(name: 'lng') String? lng,
```

2023-10-02 09:15 UTC, abiudrn commented on lib/domain/core/entities/facilities/facility_identifier.dart
>      @JsonKey(name: 'type') String? type,
This should be an enum. It could be a range of values from `MFL` or `SLADE` or `OTHER`

2023-10-02 12:26 UTC, lucyogutu approved these changes

2023-10-02 12:27 UTC, samrasugu approved these changes

2023-10-03 07:25 UTC, abiudrn approved these changes

2023-10-03 07:26 UTC, merged